
create table oauth_client_details (
  client_id VARCHAR(256) PRIMARY KEY,
  resource_ids VARCHAR(256),
  client_secret VARCHAR(256),
  scope VARCHAR(256),
  authorized_grant_types VARCHAR(256),
  web_server_redirect_uri VARCHAR(256),
  authorities VARCHAR(256),
  access_token_validity INTEGER,
  refresh_token_validity INTEGER,
  additional_information VARCHAR(4096),
  autoapprove VARCHAR(256)
);

create table oauth_client_token (
  token_id VARCHAR(256),
  token LONGVARBINARY,
  authentication_id VARCHAR(256) PRIMARY KEY,
  user_name VARCHAR(256),
  client_id VARCHAR(256)
);

create table oauth_access_token (
  token_id VARCHAR(256),
  token LONGVARBINARY,
  authentication_id VARCHAR(256) PRIMARY KEY,
  user_name VARCHAR(256),
  client_id VARCHAR(256),
  authentication LONGVARBINARY,
  refresh_token VARCHAR(256)
);

create table oauth_refresh_token (
  token_id VARCHAR(256),
  token LONGVARBINARY,
  authentication LONGVARBINARY
);

create table oauth_code (
  code VARCHAR(256), authentication LONGVARBINARY
);

create table oauth_approvals (
	userId VARCHAR(256),
	clientId VARCHAR(256),
	scope VARCHAR(256),
	status VARCHAR(10),
	expiresAt TIMESTAMP,
	lastModifiedAt TIMESTAMP
);


-- customized oauth_client_details table
create table ClientDetails (
  appId VARCHAR(256) PRIMARY KEY,
  resourceIds VARCHAR(256),
  appSecret VARCHAR(256),
  scope VARCHAR(256),
  grantTypes VARCHAR(256),
  redirectUrl VARCHAR(256),
  authorities VARCHAR(256),
  access_token_validity INTEGER,
  refresh_token_validity INTEGER,
  additionalInformation VARCHAR(4096),
  autoApproveScopes VARCHAR(256)
);



INSERT into SEC_USUARIOS(ADMINISTRADOR, CLAVE, CLAVE_GENERADA, CODCIA, CODIGO_SEGURIDAD, CODUSR, ESTADO_CLAVE, FECHA_ULTIMA_MODIFICACION, FECHA_VENCIMIENTO_CLAVE, NOMBRE, VALIDAR_IP, ESTADO) 
values(2,'$2a$10$pDBBaL0g/7epijof.0KYy.8sBQPqNEBhgcrRU2/PYMlUXseNdnjwa', '', 1, 0, 'javalos', 'A', '2019-12-10 16:44:33.115', '2020-01-05 00:00:00', 'Julio Amadeo Avalos Urquiza', 'N', '1');

INSERT into SEC_USUARIOS(ADMINISTRADOR, CLAVE, CLAVE_GENERADA, CODCIA, CODIGO_SEGURIDAD, CODUSR, ESTADO_CLAVE, FECHA_ULTIMA_MODIFICACION, FECHA_VENCIMIENTO_CLAVE, NOMBRE, VALIDAR_IP, ESTADO) 
values(2,'$2a$10$pDBBaL0g/7epijof.0KYy.8sBQPqNEBhgcrRU2/PYMlUXseNdnjwa', '', 1, 0, 'dummy', 'A', '2019-12-10 16:44:33.115', '2020-01-05 00:00:00', 'Dummy User', 'N','1');

INSERT into SEC_USUARIOS(ADMINISTRADOR, CLAVE, CLAVE_GENERADA, CODCIA, CODIGO_SEGURIDAD, CODUSR, ESTADO_CLAVE, FECHA_ULTIMA_MODIFICACION, FECHA_VENCIMIENTO_CLAVE, NOMBRE, VALIDAR_IP,ESTADO) 
values(2,'$2a$10$pDBBaL0g/7epijof.0KYy.8sBQPqNEBhgcrRU2/PYMlUXseNdnjwa', '', 1, 0, 'test', 'A', '2019-12-10 16:44:33.115', '2020-01-05 00:00:00', 'Test User', 'N','1');


INSERT INTO ARTICULO(DESCRIPCION, FECHA_HORA_CREACION, ULTIMO_COSTO) VALUES('7UP', parsedatetime('09-07-2014 17:00:12.57', 'dd-MM-yyyy hh:mm:ss.SS'), 7.99);
INSERT INTO ARTICULO(DESCRIPCION, FECHA_HORA_CREACION, ULTIMO_COSTO) VALUES('Chocolate Blanco',parsedatetime('25-05-2016 11:22:32.69', 'dd-MM-yyyy hh:mm:ss.SS'), 5.99);
INSERT INTO ARTICULO(DESCRIPCION, FECHA_HORA_CREACION, ULTIMO_COSTO) VALUES('Monopoly',parsedatetime('17-02-2012 18:58:52.30', 'dd-MM-yyyy hh:mm:ss.SS'), 14.99);
INSERT INTO ARTICULO(DESCRIPCION, FECHA_HORA_CREACION, ULTIMO_COSTO) VALUES('Cubo Rubik',parsedatetime('30-12-2012 14:47:52.24', 'dd-MM-yyyy hh:mm:ss.SS'), 9.99);

insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Fondant - Icing', 73.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Sticks, Thin, Plain', 98.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Hinge 117n', 96.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ham - Procutinni', 48.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Anchovy In Oil', 54.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Burger', 62.8);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Top Sirloin', 79.03);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Couscous', 58.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Caul Fat', 94.77);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread Base - Toscano', 58.46);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tart - Raisin And Pecan', 47.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mushroom - Chanterelle, Dry', 96.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Fib N9 - Prague Powder', 66.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Latex Rubber Gloves Size 9', 16.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pie Filling - Pumpkin', 87.9);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pan Grease', 34.11);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Shrimp - Baby, Cold Water', 82.9);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chambord Royal', 59.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Coteaux Du Tricastin Ac', 35.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rum - Cream, Amarula', 52.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cucumber - Pickling Ontario', 61.19);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Lemon', 32.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Hardys Bankside Shiraz', 68.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Brandy Apricot', 72.56);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Magnotta - Pinot Gris Sr', 68.35);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Triangle White', 79.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flour - Masa De Harina Mexican', 70.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Longos - Grilled Veg Sandwiches', 58.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb Shoulder Boneless Nz', 20.35);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rice - Aborio', 79.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Red Snapper - Fillet, Skin On', 82.4);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coffee Guatemala Dark', 85.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coffee Decaf Colombian', 50.54);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Container - Clear 16 Oz', 73.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nut - Chestnuts, Whole', 98.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Corn Shoots', 96.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sugar - Brown', 44.77);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Potatoes - Fingerling 4 Oz', 39.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells, Creamy', 76.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Potatoes - Fingerling 4 Oz', 76.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells Beef Strogonoff', 43.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Penne Primavera, Single', 48.49);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Bones', 91.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Ocean Spray Cranberry', 41.96);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Anchovy Fillets', 16.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rum - Light, Captain Morgan', 63.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beans - Yellow', 18.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - Tetleys', 23.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pastrami', 26.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Artichoke - Fresh', 28.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nut - Pine Nuts, Whole', 38.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Montreal Smoked Brisket', 65.17);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Chili Powder', 50.75);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Isomalt', 50.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rosemary - Dry', 16.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bagel - Ched Chs Presliced', 69.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Bacon Cooked Slcd', 44.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sugar - Individual Portions', 52.11);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lobster - Tail 6 Oz', 51.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mushroom - Porcini, Dry', 64.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bols Melon Liqueur', 51.31);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pea - Snow', 76.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soupfoamcont12oz 112con', 83.11);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Batt - Carrot Spice', 96.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Fettuccine, Dry', 65.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('French Pastries', 15.12);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Gatorade - Xfactor Berry', 49.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Spinach - Packaged', 93.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Alize Sunset', 81.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chinese Foods - Pepper Beef', 34.69);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Fish - Halibut, Cold Smoked', 61.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Cotes Du Rhone', 44.87);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Tenderloin, Fresh', 57.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Red Thai', 70.56);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Victor Et Berthold', 33.9);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Worcestershire Sauce', 36.17);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Snapple - Mango Maddness', 41.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lumpfish Black', 28.3);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Clavet Saint Emilion', 92.54);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ginger - Pickled', 98.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Honey - Lavender', 72.23);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Salt - Celery', 62.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Jameson Irish Whiskey', 60.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chocolate - Mi - Amere Semi', 42.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Olives - Nicoise', 64.87);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cookies - Englishbay Oatmeal', 78.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Drambuie', 99.35);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tea - Orange Pekoe', 64.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pastry - Raisin Muffin - Mini', 72.36);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Red Bell', 47.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tea - Lemon Green Tea', 27.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nantucket - Kiwi Berry Cktl.', 30.02);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carbonated Water - Blackberry', 83.23);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Cubanelle', 35.75);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Potatoes - Mini White 3 Oz', 55.44);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - Pilsner Urquell', 96.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flour - Bread', 84.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Toasted Head', 77.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wonton Wrappers', 77.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tomatoes Tear Drop', 48.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Okra', 90.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Scallops - U - 10', 91.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cup - 3.5oz, Foam', 48.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Basil - Primerba, Paste', 75.69);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Chateau Bonnet', 76.6);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Shank', 72.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Brie, Cups 125g', 50.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Celery Root', 36.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Red, Black Opal Shiraz', 33.69);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Puff Pastry - Slab', 40.19);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carrots - Mini Red Organic', 75.69);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chocolate - Feathers', 87.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Gherkin - Sour', 73.5);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Kiwano', 50.37);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Bistro White', 94.15);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Silicone Paper 16.5x24', 78.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pie Filling - Pumpkin', 50.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Pinot Noir Latour', 53.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Icecream - Dibs', 81.03);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Ground', 97.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Hickory Smoke, Liquid', 55.75);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Prime Rib Aaa', 29.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Pinot Grigio Collavini', 29.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Propel Sport', 55.69);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mushroom - Morels, Dry', 86.68);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin - Bran Ind Wrpd', 34.46);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Sauvignon Blanc', 83.44);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Truffle - Whole Black Peeled', 79.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Curry Powder', 19.69);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells, Lentil', 69.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - 10 Grain Parisian', 92.6);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bag Clear 10 Lb', 59.44);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Red Currant Jelly', 67.82);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lychee', 83.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Towel Dispenser', 83.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Energy - Boo - Koo', 64.47);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cranberry Foccacia', 45.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carbonated Water - Raspberry', 47.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Mix - Raisin Bran', 92.6);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Worcestershire Sauce', 85.2);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tea - Honey Green Tea', 59.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flour - Pastry', 45.35);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pear - Prickly', 19.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread Foccacia Whole', 18.7);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Liquid Aminios Acid - Braggs', 23.5);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Compound - Orange', 81.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Shark - Loin', 84.7);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ice Cream Bar - Drumstick', 47.56);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Grapes - Green', 47.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beets - Candy Cane, Organic', 99.34);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cookies Almond Hazelnut', 92.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chicken - Ground', 33.34);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Turkey Leg With Drum And Thigh', 98.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Red, Metus Rose', 33.95);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Hold Up Tool Storage Rack', 28.29);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Broom - Push', 62.52);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Icecream - Dstk Strw Chseck', 32.15);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Trout - Smoked', 84.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cardamon Seed / Pod', 40.87);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beans - Black Bean, Preserved', 64.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('V8 Splash Strawberry Kiwi', 25.65);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rice - Long Grain', 38.27);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Napkin - Dinner, White', 23.75);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pesto - Primerba, Paste', 57.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bag Stand', 56.85);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('English Muffin', 28.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bag - Clear 7 Lb', 82.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pancetta', 19.65);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Compound - Orange', 91.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('V8 - Berry Blend', 26.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Onions - Green', 35.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Roll, Italian', 74.69);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Pineapple, 341 Ml', 35.23);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sunflower Seed Raw', 83.09);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sugar - Fine', 54.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Cotes Du Rhone Parallele', 55.87);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nut - Pumpkin Seeds', 96.25);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Icecream Bar - Del Monte', 50.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coriander - Ground', 58.77);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Kiwi', 55.95);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ecolab - Mikroklene 4/4 L', 92.85);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Butter - Unsalted', 27.97);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Shrimp - 150 - 250', 30.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chick Peas - Canned', 20.19);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Ruffino Chianti Classico', 28.85);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flour - All Purpose', 99.16);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mop Head - Cotton, 24 Oz', 48.66);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Onions - Red Pearl', 31.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Cow Feet Split', 37.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Schnappes - Peach, Walkers', 57.38);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Hock And Feet Attached', 18.03);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Flank Steak', 52.2);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Shrimp - Baby, Warm Water', 30.16);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pesto - Primerba, Paste', 26.46);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sugar - Sweet N Low, Individual', 58.24);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Red Chili', 67.66);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Fat Bastard Merlot', 54.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Plate - Foam, Bread And Butter', 41.49);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cornflakes', 70.75);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Sour Batard', 33.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Stock - Beef, White', 31.34);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Capicola - Hot', 76.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Fett Alfredo, Single Serve', 55.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nut - Macadamia', 36.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sauce - Salsa', 57.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mini - Vol Au Vents', 86.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tarragon - Fresh', 82.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Puree - Strawberry', 57.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('The Pop Shoppe - Black Cherry', 94.5);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Scallops - In Shell', 17.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chinese Foods - Pepper Beef', 32.15);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Venison - Ground', 80.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Mix - Chocolate Chip', 65.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Aspic - Clear', 74.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb - Pieces, Diced', 24.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pastry - Butterscotch Baked', 30.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sauce - Demi Glace', 98.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Marlbourough Sauv Blanc', 51.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Shrimp - Black Tiger 16/20', 18.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Magnotta - Bel Paese White', 33.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sobe - Green Tea', 90.79);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soupfoamcont12oz 112con', 15.11);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Bones', 31.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mudslide', 28.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Transfer Sheets', 47.37);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Venison - Denver Leg Boneless', 86.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lemons', 54.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Orange Individual', 18.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cookies - Fortune', 27.88);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Yogurt - Assorted Pack', 61.52);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lettuce - Spring Mix', 59.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Swiss Sliced', 83.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Onions Granulated', 56.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - White, Lindemans Bin 95', 97.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ketchup - Tomato', 44.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Jafflin Bourgongone', 48.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Belly Fresh', 48.46);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lemonade - Strawberry, 591 Ml', 16.6);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beets - Candy Cane, Organic', 20.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lid - 0090 Clear', 47.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oneshot Automatic Soap System', 71.07);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb - Shoulder, Boneless', 95.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Two Oceans Cabernet', 47.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tea - Grapefruit Green Tea', 42.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells', 80.9);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Sushi Flat Iron Steak', 21.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Squid - U - 10 Thailand', 44.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cream - 18%', 85.75);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oil - Sunflower', 99.66);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Melon - Honey Dew', 61.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chutney Sauce', 87.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Gatorade - Lemon Lime', 42.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Island Oasis - Raspberry', 58.36);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('White Fish - Filets', 29.71);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Crackers - Trio', 25.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Island Oasis - Sweet And Sour Mix', 56.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sauce - Roasted Red Pepper', 40.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Truffle Shells - White Chocolate', 21.66);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Steel Wool S.o.s', 46.19);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sausage - Andouille', 56.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Verve - Chipotle Chicken', 72.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oil - Olive', 31.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cornstarch', 41.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Onions - Green', 77.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chicken - Wieners', 80.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Syrup - Chocolate', 80.65);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pie Box - Cello Window 2.5', 75.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Stock - Veal, White', 26.07);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mushroom - Enoki, Fresh', 25.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Edible Flower - Mixed', 70.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Crackers - Melba Toast', 84.16);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Swiss', 79.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Trueblue - Blueberry Cranberry', 25.79);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nantucket - Kiwi Berry Cktl.', 65.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Grenadillo', 21.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cloves - Whole', 92.77);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flour - Strong Pizza', 81.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nut - Pine Nuts, Whole', 70.46);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Plastic Wrap', 84.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chestnuts - Whole,canned', 58.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Two Oceans Cabernet', 79.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oil - Sunflower', 82.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rosemary - Fresh', 57.49);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Boston Clam Chowder', 67.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Red, Black Opal Shiraz', 55.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Brie', 76.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Dried Peach', 77.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bols Melon Liqueur', 88.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Salmon - Atlantic, Skin On', 35.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Red, Cabernet Merlot', 89.79);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb - Shoulder, Boneless', 87.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cleaner - Lime Away', 25.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Parmesan Grated', 82.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pastry - Apple Muffins - Mini', 46.8);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Energy - Boo - Koo', 96.85);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Appetizer - Sausage Rolls', 87.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cookies - Amaretto', 73.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pear - Halves', 57.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Zonnebloem Pinotage', 74.7);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Orange, Concentrate', 22.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Halibut - Whole, Fresh', 62.79);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - St. Paulin', 81.27);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Venison - Racks Frenched', 85.95);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beans - Black Bean, Canned', 25.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Salmon - Fillets', 95.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Alsace Gewurztraminer', 51.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Rosso Toscano Igt', 56.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Dish Towel', 80.93);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - White, Riesling, Semi - Dry', 41.37);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sole - Iqf', 60.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mousse - Banana Chocolate', 99.85);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Pita', 64.4);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Jolt Cola', 74.29);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Glass Clear 8 Oz', 38.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Asiago', 37.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Salt - Celery', 72.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chinese Foods - Chicken', 87.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Pita', 35.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - White, Schroder And Schyl', 42.49);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Verve - Chipotle Chicken', 63.52);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lady Fingers', 64.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soap - Hand Soap', 69.52);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flax Seed', 21.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lettuce - Boston Bib', 93.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Shiraz South Eastern', 97.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Saint - Bris 2002, Sauv', 91.44);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Crab - Imitation Flakes', 54.71);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Prem Select Charddonany', 74.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coffee Beans - Chocolate', 62.98);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Perron Cheddar', 21.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Plasticknivesblack', 95.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Cheese / Spinach Bauletti', 90.47);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mayonnaise - Individual Pkg', 96.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Jafflin Bourgongone', 40.85);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pie Filling - Cherry', 82.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sauerkraut', 24.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Black Currants', 31.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup V8 Roasted Red Pepper', 55.88);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Yeast Dry - Fleischman', 17.13);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb - Leg, Boneless', 15.38);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Aromat Spice / Seasoning', 44.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Vol Au Vents', 94.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Dried Apple', 71.49);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Loin, Center Cut', 94.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tuna - Sushi Grade', 43.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Garlic Powder', 27.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Appetizer - Asian Shrimp Roll', 24.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Napkin - Beverage 1 Ply', 97.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pecan Raisin - Tarts', 63.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Napkin White', 40.27);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coffee - Almond Amaretto', 17.85);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pineapple - Golden', 20.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Foil - Round Foil', 72.16);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - Muskoka Cream Ale', 89.36);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Jack Daniels', 61.09);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese Cloth', 48.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chicken - Base', 15.77);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chips - Assorted', 33.66);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Marjoram - Fresh', 18.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lemons', 80.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Bacon, Double Smoked', 89.6);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Longos - Grilled Salmon With Bbq', 84.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Maintenance Removal Charge', 66.52);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Bones', 58.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sausage - Chorizo', 55.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tray - 16in Rnd Blk', 41.23);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lambcasing', 84.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Provolone', 46.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sobe - Orange Carrot', 63.97);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Peas - Pigeon, Dry', 80.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Vinegar - Balsamic, White', 25.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Stock - Beef, White', 41.47);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Lasagna Noodle, Frozen', 89.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Pinot Noir Stoneleigh', 46.3);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Shiratamako - Rice Flour', 32.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Striploin', 62.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Frozen Basket Variety', 90.52);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Goat - Leg', 97.12);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Beef Conomme, Dry', 64.46);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Doilies - 5, Paper', 24.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carrots - Purple, Organic', 51.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carrots - Mini Red Organic', 18.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Guy Sage Touraine', 63.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Appetizer - Chicken Satay', 35.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Fat Bastard Merlot', 65.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Barbera Alba Doc 2001', 80.96);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Curry Powder Madras', 92.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sponge Cake Mix - Chocolate', 74.97);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Corn Syrup', 44.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Curry Paste - Green Masala', 46.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flounder - Fresh', 47.25);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Apple - Fuji', 74.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sage - Fresh', 60.12);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nut - Hazelnut, Whole', 32.25);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Two Oceans Sauvignon', 65.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soda Water - Club Soda, 355 Ml', 46.03);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mousse - Passion Fruit', 90.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Arizona - Plum Green Tea', 30.49);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Grapefruit, 341 Ml', 26.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Yogurt - Peach, 175 Gr', 64.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chilli Paste, Sambal Oelek', 41.3);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Cava Aria Estate Brut', 62.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Rib Roast, Capless', 84.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells, Cream Of', 17.55);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Manchego, Spanish', 74.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal - Brisket, Provimi,bnls', 23.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal - Loin', 20.54);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tart - Lemon', 29.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Rib Roast, Capless', 88.38);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Saint Emilion Calvet', 37.13);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Provolone', 95.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rambutan', 66.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Multigrain', 99.96);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mushroom - Porcini Frozen', 70.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Mas Chicet Rose, Vintage', 49.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tea - Honey Green Tea', 50.69);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Broccoli - Fresh', 39.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Green Tea Refresher', 15.52);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pastry - Banana Muffin - Mini', 85.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Parmigiano Reggiano', 45.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Elbows, Macaroni, Dry', 85.27);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Duboeuf Beaujolais', 29.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mousse - Mango', 30.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Fondant - Icing', 24.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cognac - Courvaisier', 68.11);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - Blue', 90.68);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Cheddar, Mild', 87.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Eggplant Italian', 43.12);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tarts Assorted', 77.06);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mushroom - Porcini Frozen', 39.06);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Vidal Icewine Magnotta', 33.98);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Basil - Seedlings Cookstown', 42.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Two Oceans Sauvignon', 37.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ice Cream - Turtles Stick Bar', 54.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tea - Camomele', 66.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chips Potato Salt Vinegar 43g', 72.75);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tomatoes - Diced, Canned', 93.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Rosemary Focaccia', 39.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mushroom Morel Fresh', 55.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Puck Ww Carrot', 83.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Melon - Cantaloupe', 31.96);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Lasagna, Dry', 47.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Alsace Gewurztraminer', 28.75);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oil - Safflower', 52.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lemonade - Island Tea, 591 Ml', 36.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lemon Tarts', 42.49);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Hickory Smoke, Liquid', 95.98);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Remy Red', 78.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb - Leg, Bone In', 24.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Trueblue - Blueberry', 17.4);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Le Cru Du Clocher', 64.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tea - Darjeeling, Azzura', 78.97);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - La Sauvagine', 46.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Halibut - Whole, Fresh', 17.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oneshot Automatic Soap System', 47.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells Chicken', 69.31);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flavouring - Orange', 49.85);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Glass - Wine, Plastic, Clear 5 Oz', 19.6);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Sorrano', 76.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lettuce - Lambs Mash', 65.5);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Appetizer - Escargot Puff', 26.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ostrich - Fan Fillet', 72.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pastry - Trippleberry Muffin - Mini', 83.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Hummus - Spread', 80.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Stock - Veal, Brown', 20.16);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sugar - Fine', 22.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Red, Metus Rose', 92.12);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal - Loin', 40.65);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chicken - Livers', 18.56);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chickhen - Chicken Phyllo', 38.17);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Montery Jack', 27.16);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chocolate Bar - Smarties', 16.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork Casing', 24.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tuna - Bluefin', 90.7);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Apple - Northern Spy', 90.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pur Source', 30.17);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Steam Pan - Half Size Deep', 16.34);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sponge Cake Mix - Vanilla', 56.37);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coke - Classic, 355 Ml', 18.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Broom - Angled', 98.16);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Irish Cream - Butterscotch', 36.11);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Onions - Green', 16.31);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Kiwano', 55.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal - Ground', 69.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Straw - Regular', 65.03);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mcguinness - Blue Curacao', 42.13);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Cream Of Potato / Leek', 20.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Hold Up Tool Storage Rack', 21.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - Corona', 18.96);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Apple - Custard', 74.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Hinge 117n', 39.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Kwv Chenin Blanc South', 94.09);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Horseradish - Prepared', 32.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Avocado', 96.55);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Corn Shoots', 72.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Jackson Triggs Okonagan', 24.06);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Otomegusa Dashi Konbu', 79.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Buffalo - Short Rib Fresh', 75.49);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Leeks - Large', 20.17);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Magnotta - Bel Paese White', 41.65);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Breadfruit', 26.93);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sandwich Wrap', 43.8);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Bones, Cut - Up', 77.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Canadian Emmenthal', 67.38);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Miso Paste White', 87.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lid Coffee Cup 8oz Blk', 30.3);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coffee Caramel Biscotti', 20.87);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Gooseberry', 86.68);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal - Shank, Pieces', 86.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tofu - Soft', 64.8);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Batt - Carrot Spice', 70.65);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Comtomme', 87.19);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Puree - Pear', 78.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cauliflower', 46.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Appetizer - Mango Chevre', 26.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bagel - Plain', 22.27);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chicken - Livers', 20.47);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beans - Soya Bean', 72.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('V8 Splash Strawberry Banana', 88.11);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - Sleemans Cream Ale', 37.34);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mushroom - Lg - Cello', 18.37);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Kellogs Raisan Bran Bars', 22.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nut - Pistachio, Shelled', 68.98);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tofu - Soft', 49.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cocoa Powder - Dutched', 19.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Sushi Flat Iron Steak', 70.9);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Bistro Sour', 16.15);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Goldschalger', 28.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Vinegar - Rice', 63.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Campari', 82.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Table Cloth 90x90 Colour', 15.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Jam - Strawberry, 20 Ml Jar', 46.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Basil - Seedlings Cookstown', 70.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Red, Mouton Cadet', 65.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Sushi Flat Iron Steak', 46.13);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Cheese / Spinach Bauletti', 22.54);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mix Pina Colada', 96.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Food Colouring - Green', 92.2);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Scallop - St. Jaques', 91.97);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tea - Honey Green Tea', 47.23);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Puree - Raspberry', 78.55);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cattail Hearts', 57.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Potatoes - Idaho 80 Count', 88.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - True North Lager', 98.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bagelers - Cinn / Brown', 59.11);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Yoplait Drink', 58.23);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Cream Of Broccoli', 32.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flour - Cake', 27.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Bagels, Mini', 57.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tomatillo', 55.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Vineland Estate Semi - Dry', 24.31);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Smoked Kassler', 61.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chocolate - Milk Coating', 77.44);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rappini - Andy Boy', 43.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Magnotta, White', 18.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Clam - Cherrystone', 65.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb - Loin Chops', 85.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Water - Green Tea Refresher', 51.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chinese Foods - Chicken', 88.46);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Anchovy In Oil', 20.85);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soap - Mr.clean Floor Soap', 78.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chocolate - White', 67.75);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Grapefruit - White', 89.31);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chips Potato Reg 43g', 65.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Cooked, Corned', 20.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Island Oasis - Strawberry', 92.47);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beans - Green', 82.24);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Black, Whole', 75.29);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chambord Royal', 29.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Pain Au Liat X12', 69.24);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cinnamon - Stick', 99.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Curry Paste - Green Masala', 79.68);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Bourgogne 2002, La', 76.79);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Squid - U 5', 59.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coffee Cup 8oz 5338cd', 39.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Magnotta, Merlot Sr Vqa', 66.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lettuce - Romaine', 33.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Apples - Sliced / Wedge', 38.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nori Sea Weed - Gold Label', 92.98);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Peach - Halves', 80.17);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal - Kidney', 17.24);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread Country Roll', 22.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sprouts - Baby Pea Tendrils', 44.27);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Crusty Italian Poly', 86.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Salt - Sea', 54.38);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Garlic Powder', 24.7);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mustard - Individual Pkg', 58.9);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal - Brisket, Provimi,bnls', 67.87);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bay Leaf', 32.97);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - Blue', 90.11);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flour - So Mix Cake White', 15.46);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sesame Seed', 75.29);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sponge Cake Mix - Chocolate', 23.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lemon Pepper', 25.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Truffle Cups - White Paper', 24.02);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beans - Butter Lrg Lima', 68.95);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tortillas - Flour, 12', 31.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Mix - Chocolate Chip', 21.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carbonated Water - Strawberry', 69.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbellschix Stew', 40.2);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Suckling Pig', 67.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Pinot Noir Mondavi Coastal', 72.03);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tumeric', 98.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Trueblue - Blueberry', 82.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carrots - Purple, Organic', 29.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Allspice - Jamaican', 88.23);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rum - White, Gg White', 72.27);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pear - Packum', 20.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pastry - Banana Muffin - Mini', 72.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cookie Trail Mix', 42.38);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Happy Planet', 46.56);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb - Racks, Frenched', 90.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Boogies', 29.8);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Carrot - Individual', 72.96);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Radish', 68.7);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carbonated Water - Peach', 26.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Plate Pie Foil', 90.56);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Edible Flower - Mixed', 95.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - George Duboeuf Rose', 92.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Lime', 84.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sobe - Berry Energy', 34.4);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lemon Grass', 42.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sauce - Marinara', 63.02);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Suckling Pig', 93.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Milk - 1%', 48.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oil - Olive Bertolli', 54.98);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chocolate - Feathers', 52.87);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Dry Ice', 91.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - Sleemans Cream Ale', 83.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pimento - Canned', 84.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Foil - Round Foil', 67.88);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Plastic Wrap', 58.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oranges', 39.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pop Shoppe Cream Soda', 60.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Tortellini, Fresh', 54.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pea - Snow', 27.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Salt - Celery', 76.95);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sprouts - China Rose', 68.35);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cake - Night And Day Choclate', 18.49);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pancetta', 84.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chinese Lemon Pork', 78.93);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Happy Planet', 95.38);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Appetizer - Seafood Assortment', 99.13);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lettuce - Mini Greens, Whole', 91.88);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup Campbells - Tomato Bisque', 51.77);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carbonated Water - Raspberry', 72.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chickensplit Half', 99.09);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal Inside - Provimi', 44.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Worcestershire Sauce', 65.19);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Eel - Smoked', 25.02);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Roasted Red', 65.16);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sea Bass - Fillets', 57.24);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Cubanelle', 82.36);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Knorr, Country Bean', 89.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nut - Cashews, Whole, Raw', 88.66);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sobe - Liz Blizz', 26.88);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Victor Et Berthold', 45.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Red, Marechal Foch', 66.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Assorted Desserts', 35.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oil - Olive, Extra Virgin', 43.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Country Roll', 71.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Eggplant - Regular', 66.54);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bag Clear 10 Lb', 45.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mustard - Seed', 53.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sugar - Splenda Sweetener', 96.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rice - Sushi', 86.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Capers - Pickled', 83.54);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Augre Des Champs', 37.34);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Towel Multifold', 78.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Halibut - Whole, Fresh', 70.24);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sponge Cake Mix - Chocolate', 33.44);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - White, Mosel Gold', 76.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chambord Royal', 48.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lid - 0090 Clear', 48.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mix - Cocktail Ice Cream', 48.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Squid - Breaded', 43.54);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Southern Comfort', 99.82);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Multigrain', 23.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Star Fruit', 62.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sachet', 39.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ham - Cooked Bayonne Tinned', 17.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pie Filling - Cherry', 61.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb Rack Frenched Australian', 25.8);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells, Classic Chix', 88.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Fusili Tri - Coloured', 61.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Sausage Casing', 66.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Glaze - Apricot', 66.85);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Scallops - U - 10', 77.36);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Water - San Pellegrino', 49.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal - Chops, Split, Frenched', 45.71);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Scrubbie - Scotchbrite Hand Pad', 28.19);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Cava Aria Estate Brut', 58.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Montery Jack', 41.76);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Batt - Blueberry Passion', 26.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Brick With Pepper', 69.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Taro Leaves', 37.25);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Ej Gallo Sierra Valley', 42.8);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chocolate - Compound Coating', 27.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Duck - Breast', 52.06);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells, Minestrone', 91.46);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Salt - Sea', 36.09);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Placido Pinot Grigo', 99.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread Fig And Almond', 89.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Puree - Pear', 56.44);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells, Creamy', 22.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pear - Asian', 81.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Laundry - Bag Cloth', 93.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Prime Rib Aaa', 22.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread Foccacia Whole', 68.88);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Clementine', 83.82);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Shrimp - Black Tiger 26/30', 44.49);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beets - Mini Golden', 61.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Mix - Morning Glory', 51.4);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Fettuccine, Egg, Fresh', 59.76);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cream - 35%', 30.29);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tuna - Sushi Grade', 20.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ham - Smoked, Bone - In', 84.68);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coconut - Shredded, Sweet', 37.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Scallop - St. Jaques', 50.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Star Fruit', 40.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cookie - Oreo 100x2', 19.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Apple, 341 Ml', 45.17);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Alize Sunset', 33.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb - Racks, Frenched', 58.13);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells Beef Stew', 52.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Vermouth - White, Cinzano', 67.29);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Onions - Cippolini', 62.93);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sponge Cake Mix - Vanilla', 61.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Black Tower Qr', 71.36);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sauce - Bernaise, Mix', 71.6);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Shrimp - Baby, Warm Water', 74.34);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - St. Paulin', 68.38);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sobe - Tropical Energy', 43.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Gouda Smoked', 87.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Yogurt - Raspberry, 175 Gr', 77.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chocolate - Semi Sweet, Calets', 21.8);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Sticks, Thin, Plain', 73.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Vinegar - Balsamic', 80.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Salted', 63.41);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Orange Roughy 4/6 Oz', 22.0);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Squid Ink', 32.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lobster - Cooked', 73.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tomato - Plum With Basil', 54.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Corn - Mini', 23.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ham - Black Forest', 96.19);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Pinot Noir Stoneleigh', 37.56);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chambord Royal', 67.55);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bagelers - Cinn / Brown', 33.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tea - English Breakfast', 71.03);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Foam Espresso Cup Plain White', 86.24);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sugar - Fine', 90.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Paprika, Hungarian', 60.95);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sachet', 40.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Marzipan 50/50', 17.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Foam Tray S2', 84.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cocoa Butter', 45.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rum - Coconut, Malibu', 17.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Roe - Lump Fish, Red', 15.82);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Corn Meal', 79.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cookie Chocolate Chip With', 56.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oyster - In Shell', 74.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flower - Dish Garden', 36.7);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Top Sirloin - Aaa', 60.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mushrooms - Honey', 68.34);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Dish Towel', 70.97);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Apricots - Dried', 90.65);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup Campbells Split Pea And Ham', 81.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Emulsifier', 46.7);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Radish', 93.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Batt - Blueberry Passion', 42.29);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Gherkin', 65.65);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ginger - Pickled', 24.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Clementine', 29.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Fruit Salad Deluxe', 32.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rappini - Andy Boy', 85.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Taleggio D.o.p.', 59.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flour Pastry Super Fine', 23.7);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beans - Yellow', 41.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chicken - Livers', 22.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Orange - Blood', 98.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Detalini, White, Fresh', 93.93);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coke - Classic, 355 Ml', 65.55);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chips Potato Reg 43g', 82.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chocolate Bar - Smarties', 59.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Propel Sport Drink', 23.27);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine La Vielle Ferme Cote Du', 62.35);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chicken - Leg / Back Attach', 99.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Water - Spring 1.5lit', 30.09);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Table Cloth 72x144 White', 38.93);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mcgillicuddy Vanilla Schnap', 49.76);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Currants', 88.24);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pea - Snow', 43.88);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tuna - Bluefin', 76.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Compound - Rum', 67.37);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Onion Powder', 22.87);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Seedlings - Buckwheat, Organic', 21.44);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Squash - Pattypan, Yellow', 52.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Doilies - 10, Paper', 37.56);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Goldschalger', 16.35);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Syrup - Monin, Amaretta', 87.98);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Energy Drink - Redbull 355ml', 18.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Plasticspoonblack', 18.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pineapple - Golden', 49.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Jalapeno', 67.03);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Stock - Veal, White', 46.47);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Green, Chili', 91.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pasta - Canelloni', 90.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Cheddar, Mild', 64.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Fond - Neutral', 18.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Ocean Spray Cranberry', 50.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coffee - Colombian, Portioned', 63.61);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Grapefruit - Pink', 94.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Knorr, Chicken Noodle', 31.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Conde De Valdemar', 27.95);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pickle - Dill', 80.36);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cookies - Amaretto', 97.6);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - White, Concha Y Toro', 82.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Longos - Chicken Caeser Salad', 17.25);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin - Blueberry Individual', 52.75);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bag Clear 10 Lb', 74.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Artichokes - Knobless, White', 41.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Apple, 341 Ml', 40.16);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Glycerine', 92.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal - Brisket, Provimi,bnls', 50.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muskox - French Rack', 90.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Star Fruit', 97.36);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Worcestershire Sauce', 21.07);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oil - Sesame', 77.55);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Island Oasis - Magarita Mix', 67.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Jolt Cola - Red Eye', 84.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Appetizer - Sausage Rolls', 24.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Ground', 70.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lotus Rootlets - Canned', 91.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Magnotta - Cab Franc', 34.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mayonnaise', 35.29);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Club Soda - Schweppes, 355 Ml', 83.32);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Onion - Dried', 47.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cloves - Whole', 44.13);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Texas Style Burger', 30.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Bones, Marrow', 19.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sobe - Orange Carrot', 54.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Apple - Granny Smith', 78.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Cow Feet Split', 72.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Nut - Chestnuts, Whole', 63.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cinnamon - Stick', 52.38);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Catfish - Fillets', 99.26);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cups 10oz Trans', 54.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carrots - Mini Red Organic', 39.82);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sambuca - Opal Nera', 85.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Prosecco Valdobiaddene', 17.09);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Dooleys Toffee', 17.09);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Water - Mineral, Natural', 94.07);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Vol Au Vents', 97.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Remy Red', 91.46);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flour - So Mix Cake White', 15.96);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Eel Fresh', 41.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Ej Gallo Sierra Valley', 53.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Okra', 48.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Milk - 2%', 24.42);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Vodka - Hot, Lnferno', 89.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Knorr, Classic Can. Chili', 40.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Strawberries', 21.7);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb - Rack', 70.47);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Batt - Carrot Spice', 40.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Veal - Round, Eye Of', 60.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lid Coffeecup 12oz D9542b', 63.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Longos - Assorted Sandwich', 90.76);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup Knorr Chili With Beans', 38.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Quinoa', 93.03);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cookie Chocolate Chip With', 42.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lamb - Bones', 57.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Grouper - Fresh', 19.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Bocconcini', 39.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ecolab Silver Fusion', 82.19);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ecolab Silver Fusion', 57.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chips - Potato Jalapeno', 19.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Niagara Peninsula Vqa', 85.44);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Island Oasis - Raspberry', 65.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sobe - Tropical Energy', 26.03);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ostrich - Fan Fillet', 32.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Raisin Walnut Oval', 81.62);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lotus Leaves', 99.24);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sauce - Plum', 49.27);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Southern Comfort', 74.52);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Yeast Dry - Fleischman', 62.35);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Onions - Cippolini', 44.01);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Romano, Grated', 73.63);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Trueblue - Blueberry 12x473ml', 74.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Champagne Brut Veuve', 29.55);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Silicone Parch. 16.3x24.3', 79.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cake - Lemon Chiffon', 49.9);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Stoneliegh Sauvignon', 30.45);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ecolab - Balanced Fusion', 56.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Vinegar - White', 43.08);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Onions - Pearl', 79.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Truffle - Whole Black Peeled', 98.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Montery Jack', 89.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rice Wine - Aji Mirin', 57.66);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cake - Night And Day Choclate', 48.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - German Riesling', 53.35);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cup - 3.5oz, Foam', 46.04);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Quail - Whole, Boneless', 27.55);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Lid Coffeecup 12oz D9542b', 33.13);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - French Stick', 92.88);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Magnotta - Pinot Gris Sr', 36.37);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Squash - Sunburst', 67.71);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - White Epi Baguette', 15.96);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - Raisin', 71.09);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Dawn Professionl Pot And Pan', 67.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Versatainer Nc - 888', 17.36);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Black Currants', 86.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Loin, Boneless', 97.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Spumante Bambino White', 58.27);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soap - Hand Soap', 99.6);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Brie Roitelet', 59.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Propel Sport Drink', 60.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Madeira', 32.76);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Corn Syrup', 18.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cotton Wet Mop 16 Oz', 73.8);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carbonated Water - Strawberry', 37.84);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Swiss Sliced', 23.24);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Top Sirloin - Aaa', 46.94);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sansho Powder', 54.05);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Rum - Dark, Bacardi, Black', 82.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tart Shells - Barquettes, Savory', 74.23);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ecolab - Ster Bac', 44.13);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Tomato, 48 Oz', 46.57);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Spice - Onion Powder Granulated', 22.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Carrots - Purple, Organic', 59.56);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Food Colouring - Pink', 29.06);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Peas - Pigeon, Dry', 90.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Napkin - Cocktail,beige 2 - Ply', 88.83);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chutney Sauce - Mango', 66.13);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Scallops - Live In Shell', 69.67);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pork - Chop, Frenched', 98.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Croissant, Raw - Mini', 24.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Peach - Fresh', 18.66);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Filter - Coffee', 52.71);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Compound - Raspberry', 79.52);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Eggplant - Asian', 60.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - Blue', 67.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Appetizer - Mango Chevre', 85.98);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Raspberries - Frozen', 81.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Diced', 31.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Laundry - Bag Cloth', 23.4);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Spring Roll Veg Mini', 85.98);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Ecolab - Power Fusion', 20.2);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Mayonnaise - Individual Pkg', 36.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Chocolate - Semi Sweet', 50.73);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coffee - Decaffeinato Coffee', 98.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Jerusalem Artichoke', 32.88);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Brie Roitelet', 15.51);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beef - Short Loin', 59.36);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bread - White Epi Baguette', 83.14);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Venison - Ground', 40.86);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Vinegar - Champagne', 49.3);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oil - Coconut', 48.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Eggplant - Asian', 23.59);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Chateau Bonnet', 87.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Flour - Bran, Red', 17.92);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Vinegar - White Wine', 29.56);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bay Leaf Ground', 86.89);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Garlic Powder', 73.37);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Oil - Cooking Spray', 15.69);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Bacardi Breezer - Strawberry', 81.38);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Puree - Strawberry', 40.22);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Spice - Onion Powder Granulated', 46.48);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soda Water - Club Soda, 355 Ml', 60.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sultanas', 72.28);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Croissants Thaw And Serve', 33.68);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - White, Ground', 46.93);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Beer - Moosehead', 35.47);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Macaroons - Two Bite Choc', 84.11);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Potatoes - Idaho 80 Count', 63.39);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Quinoa', 32.44);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Mango', 21.99);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tahini Paste', 74.1);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Muffin Batt - Blueberry Passion', 98.34);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Soup - Campbells, Beef Barley', 77.06);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cream - 10%', 68.07);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cookies - Fortune', 53.91);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cheese - Wine', 21.6);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Tea - Herbal - 6 Asst', 79.74);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Cup - 6oz, Foam', 26.64);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Sun - Dried Tomatoes', 97.21);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wasabi Powder', 38.58);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Pepper - Red Chili', 15.02);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Truffle Cups - Brown', 33.3);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Apricots - Dried', 68.71);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Horseradish Root', 81.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Coconut - Shredded, Sweet', 21.18);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Dill - Primerba, Paste', 61.72);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Champagne - Brights, Dry', 15.43);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Schnappes Peppermint - Walker', 76.53);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Container - Hngd Cll Blk 7x7x3', 31.81);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Wine - Red, Harrow Estates, Cab', 19.78);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Crackers - Water', 17.33);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Juice - Orangina', 34.54);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Shrimp - 31/40', 29.3);
insert into ARTICULO (DESCRIPCION, ULTIMO_COSTO) values ('Apples - Spartan', 75.22);
